# Generated by Django 4.2.6 on 2024-03-12 11:29

import activities.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('start_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('max_participants', models.PositiveIntegerField()),
                ('activity_name', models.CharField(blank=True, max_length=64, null=True)),
                ('activity_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activity_description', models.TextField()),
                ('registration_deadline', models.DateField()),
                ('destination_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('activity_images', models.ImageField(upload_to=activities.models.upload_to, verbose_name='Images')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include_tent', models.BooleanField(default=False)),
                ('tent_price', models.CharField(blank=True, max_length=56, null=True)),
                ('difficulity_level', models.CharField(blank=True, max_length=56, null=True)),
                ('activity_type', models.CharField(blank=True, max_length=56, null=True)),
            ],
        ),
    ]
