# Generated by Django 4.2.6 on 2024-03-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activities', 'verbose_name_plural': 'Activities'},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='activity_images',
            new_name='image',
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(blank=True, max_length=56, null=True),
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='tent_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
