# Generated by Django 4.2.6 on 2024-03-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('CAMPING', 'Camping'), ('HICKING', 'Hicking')], max_length=56, null=True),
        ),
    ]
