# Generated by Django 4.2.6 on 2024-03-24 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_activity_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='members',
        ),
    ]
