# Generated by Django 4.1.13 on 2024-06-05 21:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_alter_activity_activity_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
