# Generated by Django 4.1.13 on 2024-06-05 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0011_testpolygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpolygon',
            name='activity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='activities.activitytype'),
            preserve_default=False,
        ),
    ]
