# Generated by Django 4.1.13 on 2024-06-05 21:33

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_testpolygon_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpolygon',
            name='line',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='testpolygon',
            name='multiline',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='testpolygon',
            name='multipoint',
            field=django.contrib.gis.db.models.fields.MultiPointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='testpolygon',
            name='multipoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
