# Generated by Django 4.1.13 on 2024-06-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_testpolygon_line_testpolygon_multiline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testpolygon',
            name='line',
        ),
        migrations.RemoveField(
            model_name='testpolygon',
            name='multiline',
        ),
        migrations.RemoveField(
            model_name='testpolygon',
            name='multipoly',
        ),
        migrations.RemoveField(
            model_name='testpolygon',
            name='poly',
        ),
    ]
