# Generated by Django 4.1.13 on 2024-06-09 10:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_remove_testpolygon_line_remove_testpolygon_multiline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='starting_point',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
        ),
    ]
