# Generated by Django 4.1.13 on 2024-06-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_alter_activity_starting_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='starting_point',
            new_name='point_on_map',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='destination_location',
        ),
    ]
