# Generated by Django 4.1.13 on 2024-07-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_rename_starting_point_activity_point_on_map_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestPolygon',
        ),
    ]
