# Generated by Django 4.2.6 on 2024-07-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0017_delete_testpolygon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityPhotos',
        ),
    ]
