# Generated by Django 4.1.13 on 2024-06-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_remove_acceptedreservations_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acceptedreservations',
            old_name='participant_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='rejectedreservations',
            old_name='participant_id',
            new_name='user',
        ),
    ]
