# Generated by Django 4.1.13 on 2024-03-29 03:18

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_file',
            field=models.FileField(blank=True, null=True, upload_to=articles.models.file_path),
        ),
    ]
