# Generated by Django 4.1.13 on 2024-04-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_article_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
