# Generated by Django 4.2.6 on 2024-03-24 02:33

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=members.models.upload_to, verbose_name='Images'),
        ),
    ]
