# Generated by Django 4.1.13 on 2024-06-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='work',
            field=models.CharField(max_length=128),
        ),
    ]
