# Generated by Django 4.1.13 on 2024-07-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_alter_messages_options_messages_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
