# Generated by Django 4.2.6 on 2024-01-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_city',
        ),
    ]
