# Generated by Django 4.2.6 on 2024-01-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='can_update_password',
            field=models.BooleanField(default=False),
        ),
    ]
