# Generated by Django 4.2.6 on 2024-01-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_passwordreset_can_update_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='current_city',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='emergency_number',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='martial_status',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='work',
        ),
    ]
