# Generated by Django 4.2.6 on 2024-01-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_participant_current_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_city',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_number',
            field=models.CharField(default=11, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='martial_status',
            field=models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated')], default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='work',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
