# Generated by Django 4.2.6 on 2024-01-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
