# Generated by Django 4.2.6 on 2024-02-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_city',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
