# Generated by Django 4.2.6 on 2024-02-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Members', 'verbose_name_plural': 'Members'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='membership_num',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AddField(
            model_name='member',
            name='age',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='member',
            name='current_city',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(db_index=True, default=1, max_length=254, unique=True, verbose_name='email address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(db_index=True, default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=16),
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name',
            field=models.CharField(db_index=True, default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='mid_name',
            field=models.CharField(db_index=True, default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='work',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='member',
            table=None,
        ),
    ]
