# Generated by Django 4.2.6 on 2024-02-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_member_options_remove_member_membership_num_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
