# Generated by Django 4.2.6 on 2024-02-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_delete_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_sent_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
