# Generated by Django 4.2.6 on 2024-03-06 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
