# Generated by Django 4.1.13 on 2024-07-12 21:00

from django.db import migrations
import user_preferences.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='preferred_month',
            field=user_preferences.models.MonthField(blank=True, max_length=2, null=True),
        ),
    ]
