# Generated by Django 4.1.13 on 2024-07-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_preferences', '0002_alter_preferences_preferred_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='preferred_month',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
